import { KiroPlan } from "./dslSchema.js";

export interface GeneratedCode {
  frontend: string;
  backend: string;
}

export function generateCodeFromPlan(plan: KiroPlan): GeneratedCode {
  const inputId = plan.targetComponentId || "input_1";
  const endpoint = plan.dsl.steps?.[0]?.url || "/api/send";

  const frontend = `
  // Auto-generated by Kiro
  const handleClick = async () => {
    const name = document.getElementById("${inputId}").value;
    const res = await fetch("${endpoint}", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name }),
    });
    const data = await res.json();
    console.log("Response:", data);
  };
  `;

  const backend = `
  // Express endpoint generated by Kiro
  app.post("${endpoint}", (req, res) => {
    const { name } = req.body;
    console.log("Received:", name);
    res.json({ ok: true, echo: name });
  });
  `;

  return { frontend, backend };
}
